# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 488ffa4e35d08243f51d6f7b6459450f5822fa5f2ab13c71dad83baa3574ab424c7d9ec86ca2ed1a52ca9dba5e496d2e38af6185712c0c88b9fd69028efbc524

test:
  secret_key_base: d9d7b2d75473a30d777afe881bdc2326395de13c2a37635fb59f6ca04c2d8066fccbf4ac20e1f49f7ece22383b63541b20943f656893e5f293a0725726812dd5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
